# Server
server.port=8080

# MySQL (Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/continentes_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MongoDB (Docker)
spring.data.mongodb.uri=mongodb://localhost:27017/missile_defense_stats

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# H2 Console (Optional, for debugging)
spring.h2.console.enabled=true
